### ISSUE TITLE
How can we create and audit Apostille with this sdk?

### ISSUE THREAD

**Issue by hasanaliqureshi** [QuantumMechanics/NEM-sdk#10]

**Comment by QuantumMechanics** [comment]
Hi,

I have implemented basic support on my local version and will push it very soon :)

**Comment by hasanaliqureshi** [comment]
Cool. 
As I am working on a project where I have to use it. I have also created it based on your sdk.

**Comment by QuantumMechanics** [comment]
Added:
Code: https://github.com/QuantumMechanics/NEM-sdk/blob/master/src/model/apostille.js
Doc: https://github.com/QuantumMechanics/NEM-sdk#10---apostille
Examples: https://github.com/QuantumMechanics/NEM-sdk/tree/master/examples/nodejs/apostille
