### ISSUE TITLE
How to create Multi-signature transactions?

### ISSUE THREAD

**Issue by hasanaliqureshi** [QuantumMechanics/NEM-sdk#12]
I want to create a transaction which require 2 passwords or private keys to get successfully on blockchain. Is there any documentation for that?

**Comment by evias** [comment]
You can already create multisig transactions with :
```
var trx = nem.model.objects.create("transferTransaction")("RECIPIENT", 100, "Hello");
trx.isMultisig = true;
trx.multisigAccount = "YOUR MULTISIG";

var trxEntity = nem.model.transaction.prepare("transferTransaction")(common, trx, nem.model.network.data.testnet.id);
```

you can then send the trxEntity object. 

-- 
Signing features are not yet present in the SDK and I have sent a (PR)[https://github.com/QuantumMechanics/NEM-sdk/pull/13] for this, will be soon.

Have a look at the source code you will understand how to work with the objects..
