### ISSUE TITLE
 I’m assuming that nemesis is wrong.

### ISSUE THREAD

**Issue by 44uk** [QuantumMechanics/NEM-sdk#15]
```
let nemesis = Date.UTC(2015, 2, 29, 0, 6, 25);
```
https://github.com/QuantumMechanics/NEM-sdk/blob/master/src/utils/format.js#L36

The date nemesys block is "2015-03-29 00:06:25"
http://chain.nem.ninja/#/block/1

**Comment by evias** [comment]
from here : https://www.w3schools.com/jsref/jsref_utc.asp

> Expected values are 0-11

**Comment by 44uk** [comment]
I understood. Sorry for boring pointed out.
