### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by gimyboya** [QuantumMechanics/NEM-sdk#21]
I got this error after installing [NEM-sdk](https://github.com/QuantumMechanics/NEM-sdk) in my project but i don't how to solve it and it seems related to webpack configuration. [#196](https://github.com/webpack/webpack/issues/196) because of the way the NEM-sdk use it's imports or something.
 
```
 warning in ./~/ajv/lib/async.js

96:20-33 Critical dependency: the request of a dependency is an expression

 warning  in ./~/ajv/lib/async.js

119:15-28 Critical dependency: the request of a dependency is an expression

 warning  in ./~/ajv/lib/compile/index.js

13:21-34 Critical dependency: the request of a dependency is an expression
```
Your help is highly appreciated.

**Comment by csleary** [comment]
I'm having the same issue here. I'm a bit green when it comes to Node, but this seems to be an issue with the 'ajv' dependency of the 'har-validator' module (at least it is in my case). Would be nice to get rid of those warnings.

**Comment by gimyboya** [comment]
@csleary Can you please enlighten me about the AJV package? where is it installed exactly because i got that mentioned here... and i actually solved it there as well [#66](https://github.com/vuejs-templates/pwa/issues/66)

**Comment by csleary** [comment]
I ended up updating the dependency used by the har-validator (in the project node_modules dir) by editing the har-validator package.json -- I changed the dependency version for ajv to "*", then ran `npm update --save`, which updated it to the latest version (5.2.2). Seemed to do the trick -- no more warnings.

**Comment by thomas-tran** [comment]
This issue is still occurring, please fix
