### ISSUE TITLE
I can't install new fee version sdk

### ISSUE THREAD

**Issue by mediaprogramer** [QuantumMechanics/NEM-sdk#24]
today, I installed nem-sdk  in amazon linux 
the command is below
$npm install nem-sdk

and check it by  npm list|grep nem
it shows "nem-sdk@1.4.0"

but it calculated old fee version
could you please check it again.

thank you.

**Comment by QuantumMechanics** [comment]
Hi, sorry npm wasn't updated, should be good now

**Comment by mediaprogramer** [comment]
Thank you very much!

I don't know why ,  I couldn't install by this.
"npm install nem-sdk"

but I could install by this.

"npm install -g nem-sdk "

and add this to beginning of program
module.paths.push('/home/ec2-user/.nvm/versions/node/v6.10.3/lib/node_modules');

for your information.
thanks.
