### ISSUE TITLE
Transfer & Offline Transaction examples do not work

### ISSUE THREAD

**Issue by ipavlenko** [QuantumMechanics/NEM-sdk#27]
Tried to send transaction using browser tests.
In both examples I get FAILURE_SIGNATURE_NOT_VERIFIABLE response

**Comment by QuantumMechanics** [comment]
Should be fixed in https://github.com/QuantumMechanics/NEM-sdk/commit/bff2b37ee613f5e68b05ce6d9e53d800b8da099f
