### ISSUE TITLE
Error in manual

### ISSUE THREAD

**Issue by alexeybobovsky** [QuantumMechanics/NEM-sdk#30]
Hi 
I found an error in manual for NEM-sdk in [this section](https://github.com/QuantumMechanics/NEM-sdk#101---create-an-apostille)
In the function call  _multisigAccount_  is missing in argument list: 
```
// Create the Apostille
var apostille = nem.model.apostille.create(common, "Test.txt", fileContent, "Test Apostille", nem.model.apostille.hashing["SHA256"], false, true, nem.model.network.data.testnet.id);
```

But in [example script file]( https://github.com/QuantumMechanics/NEM-sdk/blob/master/examples/nodejs/apostille/create.js) code is correct.

**Comment by QuantumMechanics** [comment]
Fixed in https://github.com/QuantumMechanics/NEM-sdk/commit/5610ee6af0ce8654a135e67c75dcf17eed838025
