### ISSUE TITLE
How to create new mosaics

### ISSUE THREAD

**Issue by takahser** [QuantumMechanics/NEM-sdk#32]
Can the NEM sdk be used to create new mosaics?

To achieve this, according to the [NEM NIS API Documentation](https://nemproject.github.io/#mosaicDefinitionCreationTransaction) a `MosaicDefinitionCreationTransaction` has to be created and published to the network. A `MosaicDefinitionCreationTransaction` object is actually just yet another `RequestPrepareAnnounce` object so it's a decoded transaction, that will be encoded into a `RequestAnnounce` transaction and then broadcasted to the NEM network by sending it to NIS.

Unfortunately I didn't find any information on how to do this with the NEM sdk.

**Comment by QuantumMechanics** [comment]
Hi,

You can do everything with the nem-sdk :)

Here is an example: https://github.com/QuantumMechanics/NEM-sdk/blob/master/examples/nodejs/createMosaic.js
