### ISSUE TITLE
Cannot send the transaction in TESTNET

### ISSUE THREAD

**Issue by deveshaggrawal19** [QuantumMechanics/NEM-sdk#48]
If I send a transaction using the example given the following error is shown. How can I broadcast?
data:
   { timeStamp: 100359685,
     error: 'Method Not Allowed',
     message: 'HTTP method POST is not supported by this URL',
     status: 405 } }

Any help would be greatly appreciated.

**Comment by evias** [comment]
Please forward more details, we cannot know what transaction you are trying to send.
