### ISSUE TITLE
Request: minified version

### ISSUE THREAD

**Issue by Xpedite** [QuantumMechanics/NEM-sdk#6]
I love the SDK :+1: but can we also get a minified js file in the dist folder please ? 

Keep up the good work !

**Comment by evias** [comment]
+1, what about this @QuantumMechanics : https://github.com/babel/babili     with this one we might be able to integrate the minifying right into the package.json. Using gulp would also work (see NanoWallet) but needs more configuration i'm sure.

Other suggestions appreciated of course! :)

**Comment by QuantumMechanics** [comment]
Hi,

Hmm I am a bit worried about this issue: https://github.com/babel/babili/issues/485

Using uglifyJS directly on the browserified should be good for now I guess

**Comment by evias** [comment]
uglify-js dependency added in https://github.com/QuantumMechanics/NEM-sdk/pull/7  and versioning process updated to, @QuantumMechanics you would only need to _npm version 1.0.1-RC4 && npm publish_

@Xpedite : maybe before QM merges the PR, you want to test the minified file? If you wish you can fork my fork and you will be able to run "npm run minify" to have the minified JS: https://github.com/evias/NEM-sdk

**Comment by Xpedite** [comment]
Sorry guys, I lost track of this. 
I guess it can be closed now since #7  has been merged.

**Comment by evias** [comment]
yep you can now run ```npm minify``` :+1:
