### ISSUE TITLE
Move dependencies to dev-dependencies

### ISSUE THREAD

**Issue by roccomuso** [QuantumMechanics/NEM-sdk#65]
Some dependencies are bundled in the [npm module](https://www.npmjs.com/package/nem-sdk?activeTab=dependencies) because they are listed under `dependencies` instead of `devDependencies`:

```json
    "babel-cli": "^6.6.5",
    "babel-preset-es2015": "^6.6.0",
    "babel-core": "^6.7.2",
    "babel-plugin-transform-inline-environment-variables": "^6.8.0",
```

**Comment by QuantumMechanics** [comment]
Fixed in cc5ba9f
