### ISSUE TITLE
endpoint defaultTestnet

### ISSUE THREAD

**Issue by iamNEMonic** [QuantumMechanics/NEM-sdk#67]
the endpoint parameter nem.model.nodes.defaultTestnet is not updating or switching to a different node. Currently 
1) 192.3.61.243 and 50.3.87.123 have been discontinued, so they are not available and will not come back
2) 104.128.226.60 and 23.223.67.85 are VPSes and thus weak servers, they might have problem after a while
3) 95.216.73.245 (HugeTestAlice.nem.ninja) and 95.216.73.243 (HugeTestAlice2.nem.ninja) are big dedicated servers, they should be fine even after running for a long time. -Bloody Rookie

**Comment by QuantumMechanics** [comment]
Fixed in a24de20
